In [1]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.set_project('pytorch-tensors-gradient')
jovian.set_colab_id('1fJ7arM56hQdH94GtYHvc6nRmdMr0JibP')

In [2]:
import torch

# Tensors

At its core, PyTorch is a library for processing `tensors`. A `tensor` is a number, vector, matrix, or any n-dimensional array. Let's create a `tensor` with a single number.

tensor with a single number

In [3]:
t1 = torch.tensor(4.)
t1

tensor(4.)

In [4]:
t1.dtype

torch.float32

Let's try creating more complex tensors.

In [5]:
# vercor
t2 = torch.tensor(list(range(6)))
t2

tensor([0, 1, 2, 3, 4, 5])

In [6]:
t2.dtype

torch.int64

In [7]:
t2.shape

torch.Size([6])

In [8]:
# Matrix

t3 = torch.tensor([
                   [10, 20],
                   [11, 21],
                   [12, 24]
])
t3

tensor([[10, 20],
        [11, 21],
        [12, 24]])

In [9]:
t3.dtype

torch.int64

In [10]:
t3.shape

torch.Size([3, 2])

In [11]:
# 3-dimentional array
t4 = torch.tensor([
                   [
                    [1, 2, 3],
                    [4, 5., 6]
                   ],
                   [
                    [7, 8, 9],
                    [10, 11, 12]
                   ]
])

t4

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])

In [12]:
t4.dtype

torch.float32

In [13]:
t4.shape

torch.Size([2, 2, 3])

Note that it's not possible to create tensors with an improper shape.

In [14]:
# Matrix
# t5 = torch.tensor([[5., 6, 11], 
#                    [7, 8], 
#                    [9, 10]])

# It's give a ValueError error.

A ValueError is thrown because the lengths of the rows [5., 6, 11] and [7, 8] don't match.

# Tensor operations and gradients
We can combine tensors with the usual arithmetic operations. Let's look at an example:

In [15]:
# create tensors
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

Let's create a new tensor y by combining these tensors.

In [16]:
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

As expected, `y` is a tensor with the value `3 * 4 + 5 = 17`. What makes PyTorch unique is that we can automatically compute the derivative of `y` w.r.t. the tensors that have `requires_grad` set to `True` i.e. w and b. This feature of PyTorch is called _autograd_ (automatic gradients).

To compute the derivatives, we can invoke the `.backward` method on our result `y`.

In [17]:
# compute dericatives
y.backward()

The derivatives of y with respect to the input tensors are stored in the .grad property of the respective tensors.

In [18]:
# Display gradients
print(f"dy/dx : {x.grad}")
print(f"dy/dw : {w.grad}")
print(f"dy/db : {b.grad}")

dy/dx : None
dy/dw : 3.0
dy/db : 1.0


As expected, `dy/dw` has the same value as `x`, i.e., `3`, and `dy/db` has the value `1`. Note that `x.grad` is `None` because `x` doesn't have `requires_grad` set to `True`. 

The "grad" in `w.grad` is short for _gradient_, which is another term for derivative. The term _gradient_ is primarily used while dealing with vectors and matrices.

## Tensor functions

Apart from arithmetic operations, the `torch` module also contains many functions for creating and manipulating tensors. Let's look at some examples.

In [19]:
# Create a tensor with a fixed value for every element
t6 = torch.full((3, 2), 42.)
t6

tensor([[42., 42.],
        [42., 42.],
        [42., 42.]])

In [20]:
# Concatenate two tensors with compatible shapes
t7 = torch.cat((t3, t6))
t7

tensor([[10., 20.],
        [11., 21.],
        [12., 24.],
        [42., 42.],
        [42., 42.],
        [42., 42.]])

In [21]:
# Compute the sin of each element
# RuntimeError: exp_vml_cpu not implemented for ‘Long’
# math funcs doesn't work with torch if value != float
t8 = torch.sin(t7)
t8

tensor([[-0.5440,  0.9129],
        [-1.0000,  0.8367],
        [-0.5366, -0.9056],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

In [22]:
# Change the shape of a tensor
t9 = t8.reshape((3, 2, 2))
t9

tensor([[[-0.5440,  0.9129],
         [-1.0000,  0.8367]],

        [[-0.5366, -0.9056],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])

You can learn more about tensor operations [here]( https://pytorch.org/docs/stable/torch.html)

# Interoperability with Numpy
Instead of reinventing the wheel, PyTorch interoperates well with Numpy to leverage its existing ecosystem of tools and libraries.



In [23]:
import numpy as np

x = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float32)
x

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

We can convert a `Numpy` array to a `PyTorch` `tensor` using `torch.from_numpy`.

In [24]:
y = torch.from_numpy(x)
y

tensor([[1., 2., 3.],
        [4., 5., 6.]])

Let's verify that the numpy array and torch tensor have similar data types.

In [25]:
x.dtype, y.dtype

(dtype('float32'), torch.float32)

We can convert a PyTorch tensor to a Numpy array using the `.numpy()` method of a tensor.

In [26]:
z = y.numpy()
z, type(z)

(array([[1., 2., 3.],
        [4., 5., 6.]], dtype=float32), numpy.ndarray)

The interoperability between PyTorch and Numpy is essential because most datasets you'll work with will likely be read and preprocessed as Numpy arrays.

You might wonder why we need a library like PyTorch at all since Numpy already provides data structures and utilities for working with multi-dimensional numeric data. There are two main reasons:

1. **Autograd**: The ability to automatically compute gradients for tensor operations is essential for training deep learning models.
2. **GPU support**: While working with massive datasets and large models, PyTorch tensor operations can be performed efficiently using a Graphics Processing Unit (GPU). Computations that might typically take hours can be completed within minutes using GPUs.


In [27]:
!pip install jovian --upgrade --quiet

In [28]:
import jovian
jovian.commit(project='PyTorch_Tensors_Gradient')

[jovian] Detected Colab notebook...
[jovian] Please enter your API key ( from https://jovian.ai/ ):
API KEY: ··········
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/boubekri/pytorch-tensors-gradient


'https://jovian.ai/boubekri/pytorch-tensors-gradient'