In [1]:
import torch

# Tensors

At its core, PyTorch is a library for processing `tensors`. A `tensor` is a number, vector, matrix, or any n-dimensional array. Let's create a `tensor` with a single number.

tensor with a single number

In [2]:
t1 = torch.tensor(4.)
t1

tensor(4.)

In [5]:
t1.dtype

torch.float32

Let's try creating more complex tensors.

In [6]:
# vercor
t2 = torch.tensor(list(range(6)))
t2

tensor([0, 1, 2, 3, 4, 5])

In [7]:
t2.dtype

torch.int64

In [8]:
t2.shape

torch.Size([6])

In [9]:
# Matrix

t3 = torch.tensor([
                   [10, 20],
                   [11, 21],
                   [12, 24]
])
t3

tensor([[10, 20],
        [11, 21],
        [12, 24]])

In [10]:
t3.dtype

torch.int64

In [11]:
t3.shape

torch.Size([3, 2])

In [13]:
# 3-dimentional array
t4 = torch.tensor([
                   [
                    [1, 2, 3],
                    [4, 5., 6]
                   ],
                   [
                    [7, 8, 9],
                    [10, 11, 12]
                   ]
])

t4

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])

In [14]:
t4.dtype

torch.float32

In [15]:
t4.shape

torch.Size([2, 2, 3])

Note that it's not possible to create tensors with an improper shape.

In [19]:
# Matrix
t5 = torch.tensor([[5., 6, 11], 
                   [7, 8], 
                   [9, 10]])

# It's give a ValueError error.

A ValueError is thrown because the lengths of the rows [5., 6, 11] and [7, 8] don't match.

# Tensor operations and gradients
We can combine tensors with the usual arithmetic operations. Let's look at an example:

In [20]:
# create tensors
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)

x, w, b

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

Let's create a new tensor y by combining these tensors.

In [21]:
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

As expected, `y` is a tensor with the value `3 * 4 + 5 = 17`. What makes PyTorch unique is that we can automatically compute the derivative of `y` w.r.t. the tensors that have `requires_grad` set to `True` i.e. w and b. This feature of PyTorch is called _autograd_ (automatic gradients).

To compute the derivatives, we can invoke the `.backward` method on our result `y`.

In [22]:
# compute dericatives
y.backward()

The derivatives of y with respect to the input tensors are stored in the .grad property of the respective tensors.

In [24]:
# Display gradients
print(f"dy/dx : {x.grad}")
print(f"dy/dw : {w.grad}")
print(f"dy/db : {b.grad}")

dy/dx : None
dy/dw : 3.0
dy/db : 1.0


As expected, `dy/dw` has the same value as `x`, i.e., `3`, and `dy/db` has the value `1`. Note that `x.grad` is `None` because `x` doesn't have `requires_grad` set to `True`. 

The "grad" in `w.grad` is short for _gradient_, which is another term for derivative. The term _gradient_ is primarily used while dealing with vectors and matrices.

## Tensor functions

Apart from arithmetic operations, the `torch` module also contains many functions for creating and manipulating tensors. Let's look at some examples.

In [25]:
# Create a tensor with a fixed value for every element
t6 = torch.full((3, 2), 42)
t6

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [29]:
# Concatenate two tensors with compatible shapes
t7 = torch.cat((t3, t6))
t7

tensor([[10, 20],
        [11, 21],
        [12, 24],
        [42, 42],
        [42, 42],
        [42, 42]])